apiVersion: v1
kind: Service
metadata:
  name: throttle-poc
spec:
  type: NodePort
  ports:
  - port: 5201
    targetPort: 5201
  selector:
    app: throttle-poc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: throttle-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: throttle-poc
  template:
    metadata:
      labels:
        app: throttle-poc
      annotations:
        kubernetes.io/ingress-bandwidth: 1M
        kubernetes.io/egress-bandwidth: 1M
    spec:
      containers:
      - name: web
        image: networkstatic/iperf3
        args: ['-s']
        ports:
        - containerPort: 5201
          name: server
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: throttle-tester
spec:
  containers:
    - name: tester
      image: networkstatic/iperf3
      command: ['/bin/sh', '-c', 'sleep infinity']
  terminationGracePeriodSeconds: 0