apiVersion: v1
kind: Pod
metadata:
  name: throttle-poc
spec:
  containers:
    - name: web
      image: savantly/throttle-poc
      ports:
        - name: web
          containerPort: 3001
          protocol: TCP
      securityContext:
       capabilities:
         add:
           - NET_ADMIN